name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: cd EntityFrameWork && dotnet restore
    - name: Build
      run: cd EntityFrameWork && dotnet build --configuration Release --no-restore
    - name: Test
      run: cd EntityFrameWork && dotnet test --no-restore --verbosity normal
